# Generated by Django 4.0.2 on 2022-02-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolio_alter_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=351, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=2000, verbose_name='Tavsifi')),
                ('orta_description', models.TextField(blank=True, max_length=3001, verbose_name='Orta Tekst')),
                ('past_description', models.TextField(blank=True, max_length=1000, verbose_name='Pastki Tavsif:')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasmi')),
                ('create_on_date', models.DateField(auto_now=True)),
                ('create_on_time', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
