# Generated by Django 4.0.2 on 2022-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='paragraph_3',
            field=models.TextField(blank=True, max_length=500, verbose_name='Paragraf 3'),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_4',
            field=models.TextField(blank=True, max_length=500, verbose_name='Paragraf 4'),
        ),
    ]
