# Generated by Django 4.0.2 on 2022-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.CharField(max_length=10)),
                ('n2', models.CharField(max_length=10)),
                ('n3', models.CharField(max_length=10)),
                ('n4', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Hisob',
                'verbose_name_plural': 'Hisob',
            },
        ),
    ]
