# Generated by Django 4.0.2 on 2022-02-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aloqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aloqa',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aloqa',
            name='create_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
