# Generated by Django 4.0.2 on 2022-02-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aloqa_create_date_aloqa_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aloqa',
            options={'verbose_name': 'Aloqa Formasi', 'verbose_name_plural': 'Aloqa Formasi'},
        ),
        migrations.AlterField(
            model_name='aloqa',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
