# Generated by Django 4.0.2 on 2022-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_aloqa_options_alter_aloqa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aloqa',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
